name: ml_algo
description: Machine learning algorithms, Machine learning models performance evaluation functionality
version: 15.5.0
homepage: https://github.com/gyrdym/ml_algo

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  injector: ^1.0.9
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  ml_dataframe: ^0.3.0
  ml_linalg: ^12.17.8
  ml_preprocessing: ^5.2.1
  quiver: ^2.0.2
  xrange: ^0.0.8

dev_dependencies:
  benchmark_harness: '>=1.0.0 <2.0.0'
  build_runner: ^1.1.2
  build_test: ^1.3.2
  mockito: ^3.0.0
  pedantic: ^1.9.2
  test: ^1.2.0
  test_coverage: ^0.5.0
